# Google Sheets 連接配置
[connections.gsheets]
# 使用 Sheet ID 而非完整 URL
spreadsheet = "1qyHWIWq3albA8czV_ZZ4ofXjP02D3rz2R9YVC4E4Fz4"

# 錯誤回饋 Sheet
feedback_spreadsheet = "1NNfKPadacJ6SDDLw9c23fmjq-26wGEeinTbWcg7-gFg"
